[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@ds-test/=lib/forge-std/lib/ds-test/src/",
  "@forge-std/=lib/forge-std/src/",
  "@account-abstraction/=lib/account-abstraction/contracts/"
  ]

[fuzz]
runs = 64
depth = 64
fail_on_revert = true 

[invariant] 
runs = 64
depth = 64 
fail_on_revert = false 


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
